### ISSUE TITLE
Seems not compatible with eslint-plugin-vue

### ISSUE THREAD

**Issue by towertop** [paleite/eslint-plugin-diff#46]
When I turn on eslint-plugin-diff with eslint-plugin-vue at the same time, a simple .vue file content keey reporting rule 'vue/comment-directive ' error.

From their document [https://eslint.vuejs.org/rules/comment-directive.html](), the problematic rule uses eslint processer API rather than other regular rules. 

![图片](https://user-images.githubusercontent.com/1001699/233013595-24dd01c3-0536-4f1e-8107-5ad7dd55972d.png)

```vue
<template>
  <div class="a-new-table"></div>
</template>
<script lang="ts">
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'ANewTable',
  setup() {
    return {}
  },
})
</script>
<style lang="less" scoped>
.a-new-table {
  background: black;
}
</style>
```

No expert on eslint and git, spend a whole hour to figure out this. Hope anyone could look into it.

**Comment by paleite** [comment]
Hi, thanks for the report.
Would you be able to provide a reproduction repo so I can investigate this further? Thanks

**Comment by levchak0910** [comment]
This plugin is implemented to work via processor, but vue plugin (same as svelte, astro, etc) have their own processor, and only 1 processor can be applied per file (not 100% sure, but most likely)

1. I tried to console.log all files which are handled by this plugins and .vue files are not amongst them

```js
// src/preprocessors.ts
const getPreProcessor = (diffFileList, staged) => (text, filename) => {
    // ...
    console.log("getPreProcessor", shouldBeProcessed, filename);
    return shouldBeProcessed ? [text] : [];
};
```

2. When forcing 

```js
overrides: [
    {
      files: [ "*.vue" ],
      processor: "diff/ci",
    },
]
```

.vue files are handled by this plugin, but not handled by eslint-plugin-vue

@paleite do you have any ideas if it possible anyhow merge these 2 plugins together?

**Comment by cakeinpanic** [comment]
Same issue with angular preprocessor `plugin:@angular-eslint/template/process-inline-templates`....

**Comment by Kombuchelada** [comment]
It was an error on our side. I was seeing eslint errors from the templates but its because we didn't add the `plugin:diff/ci` to the _*.html_ overrides section. duh.

**Comment by hejialianghe** [comment]
有解决么

**Comment by hejialianghe** [comment]
有解决么

**Comment by hejialianghe** [comment]
有解决这个问题么

**Comment by gtbuchanan** [comment]
I tried using [`eslint-merge-processors`](https://github.com/antfu/eslint-merge-processors) to combine the processors, but that doesn't seem to work either. The errors end up being duplicated. Example:

<details>
<summary>eslint.config.mjs</summary>

```typescript
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { FlatCompat } from '@eslint/eslintrc';
import tsParser from '@typescript-eslint/parser';
import { mergeProcessors } from 'eslint-merge-processors';
import diffPlugin from 'eslint-plugin-diff';
import vuePlugin from 'eslint-plugin-vue';
import vueParser from 'vue-eslint-parser';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
  resolvePluginsRelativeTo: __dirname,
});

export default [
  ...vuePlugin.configs['flat/recommended'],
  ...compat.extends('plugin:diff/staged'),
  {
    files: ['**/*.vue'],
    languageOptions: {
      parser: vueParser,
      parserOptions: {
        extraFileExtensions: ['.vue'],
        parser: tsParser,
      },
    },
    // The order of these doesn't seem to matter. Neither works
    processor: mergeProcessors([
      vuePlugin.processors['.vue'],
      diffPlugin.processors.staged,
    ])
  },
];
```
</details>

I'll try to reproduce the problem in a separate project.

Related: https://github.com/vuejs/eslint-plugin-vue/issues/2356

**Comment by gtbuchanan** [comment]
@paleite [Here's a minimal reproduction](https://github.com/gtbuchanan/eslint-plugin-diff-vue-repro). I was able to generate it with Claude Opus 4.6 after giving it access to our repository that is experiencing the problem.

**Comment by paleite** [comment]
@gtbuchanan : Thank you for those fixes. I added your proposal and a regression test to avoid this from re-appearing in the future. Version 2.1.4 includes those changes. Would appreciate feedback once you've had the chance to try it out. Again, thanks for your contributions.

**Comment by gtbuchanan** [comment]
Thank you @paleite. That fixed the previous issue. However, we just ran into a new issue when running ESLint with the `--cache` argument:

```
ESLint: 9.37.0

Error: Could not serialize processor object (missing 'meta' object).
    at Config.toJSON (/home/vsts/work/1/s/node_modules/.pnpm/eslint@9.37.0_jiti@2.6.1/node_modules/eslint/lib/config/config.js:495:10)
    at stringify (/home/vsts/work/1/s/node_modules/.pnpm/json-stable-stringify-without-jsonify@1.0.1/node_modules/json-stable-stringify-without-jsonify/index.js:25:25)
    at module.exports (/home/vsts/work/1/s/node_modules/.pnpm/json-stable-stringify-without-jsonify@1.0.1/node_modules/json-stable-stringify-without-jsonify/index.js:68:7)
    at hashOfConfigFor (/home/vsts/work/1/s/node_modules/.pnpm/eslint@9.37.0_jiti@2.6.1/node_modules/eslint/lib/cli-engine/lint-result-cache.js:56:42)
    at LintResultCache.getValidCachedLintResults (/home/vsts/work/1/s/node_modules/.pnpm/eslint@9.37.0_jiti@2.6.1/node_modules/eslint/lib/cli-engine/lint-result-cache.js:159:24)
    at LintResultCache.getCachedLintResults (/home/vsts/work/1/s/node_modules/.pnpm/eslint@9.37.0_jiti@2.6.1/node_modules/eslint/lib/cli-engine/lint-result-cache.js:110:30)
    at lintFile (/home/vsts/work/1/s/node_modules/.pnpm/eslint@9.37.0_jiti@2.6.1/node_modules/eslint/lib/eslint/eslint-helpers.js:1279:40)
    at /home/vsts/work/1/s/node_modules/.pnpm/eslint@9.37.0_jiti@2.6.1/node_modules/eslint/lib/eslint/eslint.js:616:25
    at Array.map (<anonymous>)
    at lintFilesWithoutMultithreading (/home/vsts/work/1/s/node_modules/.pnpm/eslint@9.37.0_jiti@2.6.1/node_modules/eslint/lib/eslint/eslint.js:612:13)

Oops! Something went wrong! :(
```

It appears the `meta` property is required on the processor when running in cache mode. We worked around it with this, but I'm not sure it's the correct solution:

```
processor: {
  ...await composeDiffProcessor(vue.processors['.vue']),
  meta: vue.processors['.vue'].meta,
},
```

Perhaps `composeDiffProcessor` should spread the whole `processor` argument to the output just to be safe?

**Comment by paleite** [comment]
> Perhaps `composeDiffProcessor` should spread the whole `processor` argument to the output just to be safe?

Yes, that's exactly right. Great catch! I've published 2.1.6 now that does this.

**Comment by gtbuchanan** [comment]
I think we can close this. Seems to be working pretty well to me now. Thank you for your support!
